//! bitcode support for recursive `Data` types.
//!
//! bitcode 0.6's derived coders are static mirrors of the schema, composed inline, so a
//! self-referential type would need an infinitely-sized coder. `LazyEncoder` / `LazyDecoder`
//! break that cycle: they are the user type's `Encoder` / `Decoder`, hold the coder of a same-shape
//! *mirror* type (generated by `#[cereal::derived]` and derived by bitcode itself) behind a
//! lazily-allocated `Box`, and convert values through `EncodeMirror` / `DecodeMirror`. The encode
//! mirror borrows the original's fields through [`Ref`]; it never outlives the encode call.
//!
//! Wire format: recursion is depth-stratified — each depth level owns its own column set, laid out
//! exactly where a non-recursive coder would put it. The single invariant both sides rely on is
//!
//!   * encoder: bytes are emitted iff at least one element was encoded since the last
//!     `collect_into` (tracked by `count`, *not* by whether the box exists — callers may
//!     `reserve()` and then encode nothing, e.g. `OptionEncoder::encode_vectored`);
//!   * decoder: `populate(_, 0)` reads nothing and never descends. Descending on zero would
//!     recurse forever, so this is forced, not a choice.
//!
//! This module uses bitcode's `#[doc(hidden)]` coder traits (`bitcode::__private`, defined in
//! bitcode's `src/derive/mod.rs`, present with the `derive` feature). They are not covered by
//! bitcode's stability promise: pin `bitcode = "=0.6.9"` and bump deliberately.

use core::mem::MaybeUninit;
use core::num::NonZeroUsize;
use core::ptr::NonNull;

use ::bitcode::__private::{Buffer, Decoder, Encoder, View};
use ::bitcode::{Decode, Encode, Error};

/// Implemented by `#[cereal::derived]` for recursive types.
///
/// `Enc` has `Self`'s shape with every field replaced by [`Ref<F>`], a lifetime-erased borrow.
///
/// # Safety
/// The returned mirror borrows from `self` through raw pointers. It must be consumed before
/// `self` is moved, mutated or dropped. `LazyEncoder` is the only intended caller and satisfies
/// this by encoding the mirror immediately.
pub trait EncodeMirror {
    type Enc: Encode + Copy;
    fn to_enc(&self) -> Self::Enc;
}

/// Implemented by `#[cereal::derived]` for recursive types. `Dec` is an owned mirror of `Self`.
pub trait DecodeMirror<'de>: Sized {
    type Dec: Decode<'de>;
    fn from_dec(m: Self::Dec) -> Self;
}

// ---------------------------------------------------------------------------------------------
// Ref: a borrowed `F` with an `Encode` impl (bitcode implements `Encode` for `&str` only, not
// `&T`). Lifetime-erased on purpose: bitcode_derive rewrites field lifetimes to `'static` in the
// coder struct it generates, and `<Ref<'static, Vec<T>> as Encode>::Encoder` would require
// `T: 'static` for well-formedness. A pointer newtype has no such requirement.
// ---------------------------------------------------------------------------------------------

pub struct Ref<F: ?Sized>(NonNull<F>);

impl<F: ?Sized> Ref<F> {
    /// # Safety
    /// The `Ref` must not outlive `f`, and must only be dereferenced by `RefEncoder` while `f`
    /// is not being mutated. Generated `EncodeMirror::to_enc` bodies are the only callers.
    #[inline(always)]
    pub unsafe fn new(f: &F) -> Self {
        Self(NonNull::from(f))
    }
}

impl<F: ?Sized> Clone for Ref<F> {
    #[inline(always)]
    fn clone(&self) -> Self {
        *self
    }
}
impl<F: ?Sized> Copy for Ref<F> {}

impl<F: ?Sized + Encode> Encode for Ref<F> {
    type Encoder = RefEncoder<F>;
}

pub struct RefEncoder<F: ?Sized + Encode>(F::Encoder);

impl<F: ?Sized + Encode> Default for RefEncoder<F> {
    fn default() -> Self {
        Self(Default::default())
    }
}

impl<F: ?Sized + Encode> Buffer for RefEncoder<F> {
    fn collect_into(&mut self, out: &mut Vec<u8>) {
        self.0.collect_into(out);
    }
    fn reserve(&mut self, additional: NonZeroUsize) {
        self.0.reserve(additional);
    }
}

impl<F: ?Sized + Encode> Encoder<Ref<F>> for RefEncoder<F> {
    #[inline(always)]
    fn encode(&mut self, r: &Ref<F>) {
        // SAFETY: `Ref`s are created by `EncodeMirror::to_enc` under its contract (`LazyEncoder`
        // consumes them immediately, while the borrowed value is alive and unaliased).
        self.0.encode(unsafe { r.0.as_ref() });
    }

    #[inline(always)]
    fn encode_vectored<'v>(&mut self, i: impl Iterator<Item = &'v Ref<F>> + Clone)
    where
        Ref<F>: 'v,
    {
        // The dereferenced items get a lifetime local to this call, which any `F` outlives, so
        // this needs no `F: 'v` bound. SAFETY: as in `encode`.
        self.0.encode_vectored(i.map(|r| unsafe { r.0.as_ref() }));
    }
}

// ---------------------------------------------------------------------------------------------
// LazyEncoder
// ---------------------------------------------------------------------------------------------

/// bitcode's `MAX_VECTORED_CHUNK` (a `pub const` in bitcode's private `coder` module, not
/// re-exported): `encode_vectored` iterators hold at most this many items.
const MAX_VECTORED_CHUNK: usize = 64;

/// `<T as Encode>::Encoder` for recursive `T`.
pub struct LazyEncoder<T: EncodeMirror> {
    inner: Option<Box<<T::Enc as Encode>::Encoder>>,
    /// Elements encoded since the last `collect_into`. Wire invariant: bytes iff `count > 0`.
    count: usize,
}

impl<T: EncodeMirror> Default for LazyEncoder<T> {
    fn default() -> Self {
        Self { inner: None, count: 0 }
    }
}

impl<T: EncodeMirror> LazyEncoder<T> {
    #[inline(always)]
    fn inner(&mut self) -> &mut <T::Enc as Encode>::Encoder {
        self.inner.get_or_insert_with(Default::default)
    }
}

impl<T: EncodeMirror> Buffer for LazyEncoder<T> {
    fn collect_into(&mut self, out: &mut Vec<u8>) {
        // `collect_into` clears the inner buffer, so the next cycle starts empty.
        if core::mem::take(&mut self.count) > 0 {
            self.inner().collect_into(out);
        }
    }

    fn reserve(&mut self, additional: NonZeroUsize) {
        // Must be forwarded: bitcode encoders may only `encode` after `reserve`.
        self.inner().reserve(additional);
    }
}

impl<T: EncodeMirror> Encoder<T> for LazyEncoder<T> {
    #[inline(always)]
    fn encode(&mut self, t: &T) {
        self.count += 1;
        let m = t.to_enc();
        self.inner().encode(&m);
    }

    fn encode_vectored<'a>(&mut self, mut i: impl Iterator<Item = &'a T> + Clone)
    where
        T: 'a,
    {
        // Materialize the mirrors so the derived mirror encoder sees a real slice iterator
        // (exact size_hint, cheap to re-iterate). This is what lets a recursive *struct* keep
        // bitcode's per-field vectorization; for enums bitcode's derive loops anyway.
        let mut buf = [const { MaybeUninit::<T::Enc>::uninit() }; MAX_VECTORED_CHUNK];
        let mut n = 0;
        while n < MAX_VECTORED_CHUNK {
            let Some(t) = i.next() else { break };
            // SAFETY: every mirror in `buf` is consumed below, while `i`'s items are borrowed.
            buf[n].write(t.to_enc());
            n += 1;
        }
        if n == 0 {
            return;
        }
        self.count += n;
        // SAFETY: `buf[..n]` was initialised above; `T::Enc: Copy`, so nothing needs dropping.
        let mirrors: &[T::Enc] =
            unsafe { core::slice::from_raw_parts(buf.as_ptr().cast::<T::Enc>(), n) };
        self.inner().encode_vectored(mirrors.iter());
        // Only reached if a caller violated MAX_VECTORED_CHUNK; stays correct either way.
        for t in i {
            self.encode(t);
        }
    }
}

// ---------------------------------------------------------------------------------------------
// LazyDecoder
// ---------------------------------------------------------------------------------------------

/// `<T as Decode<'de>>::Decoder` for recursive `T`.
pub struct LazyDecoder<'de, T: DecodeMirror<'de>> {
    inner: Option<Box<<T::Dec as Decode<'de>>::Decoder>>,
}

impl<'de, T: DecodeMirror<'de>> Default for LazyDecoder<'de, T> {
    fn default() -> Self {
        Self { inner: None }
    }
}

impl<'de, T: DecodeMirror<'de>> View<'de> for LazyDecoder<'de, T> {
    fn populate(&mut self, input: &mut &'de [u8], length: usize) -> Result<(), Error> {
        if length == 0 {
            // The encoder emitted nothing for zero elements. Never descend here: for a recursive
            // schema `populate(_, 0)` would recurse without end.
            return Ok(());
        }
        self.inner
            .get_or_insert_with(Default::default)
            .populate(input, length)
    }
}

impl<'de, T: DecodeMirror<'de>> Decoder<'de, T> for LazyDecoder<'de, T> {
    #[inline(always)]
    fn decode(&mut self) -> T {
        // bitcode's contract: `populate(_, length >= 1)` precedes any `decode`, so the box exists.
        let inner = self
            .inner
            .as_mut()
            .expect("LazyDecoder::decode called before populate");
        T::from_dec(inner.decode())
    }
}