[package]
name = "sourcetrait_agnostic"
description = "Platform-agnostic environment and system calls"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
directories.workspace = true
snafu.workspace       = true
shellexpand.workspace = true
derive_more.workspace = true
strum.workspace       = true

sourcetrait_stdx.workspace            = true
sourcetrait_agnostic_bridge.workspace = true
sourcetrait_twostr.workspace          = true

[target.'cfg(target_family = "unix")'.dependencies]
sourcetrait_agnostic_unix = { path = "../../../sourcetrait_common_mono/unix/crates/sourcetrait_agnostic_unix" }
[target.'cfg(target_os = "linux")'.dependencies]
sourcetrait_agnostic_linux = { path = "../../../sourcetrait_common_mono/linux/crates/sourcetrait_agnostic_linux" }
[target.'cfg(target_os = "macos")'.dependencies]
sourcetrait_agnostic_macos = { path = "../../../sourcetrait_common_mono/macos/crates/sourcetrait_agnostic_macos" }
[target.'cfg(target_os = "windows")'.dependencies]
sourcetrait_agnostic_windows = { path = "../../../sourcetrait_common_mono/windows/crates/sourcetrait_agnostic_windows" }

[dev-dependencies]
sourcetrait_testing.workspace = true

[features]
default = []
test_with_gui = []
test_with_terminal = []
