[workspace]
resolver = "3"
members = [
    "crates/sourcetrait_agnostic",
    "crates/sourcetrait_agnostic_bridge",
    "crates/sourcetrait_cereal",
    "crates/sourcetrait_cereal_macro",
    "crates/sourcetrait_chronox",
    "crates/sourcetrait_clapx",
    "crates/sourcetrait_common",
    "crates/sourcetrait_datum",
    "crates/sourcetrait_dotrepo",
    "crates/sourcetrait_gitparity",
    "crates/sourcetrait_ronx",
    "crates/sourcetrait_ronx_macro",
    "crates/sourcetrait_stdx",
    "crates/sourcetrait_sysgreen",
    "crates/sourcetrait_tomlx",
    "crates/sourcetrait_tooling",
    "crates/sourcetrait_testing",
    "crates/sourcetrait_twostr",
    "crates/sourcetrait_testing_macro",
    #"crates/draft/sourcetrait_jsonsql",
    #"crates/draft/sourcetrait_sock",
]

[workspace.package]
version = "0.0.0-3"
edition = "2024"
authors = ["SourceTrait <development@sourcetrait.com"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_common"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "common"]

[workspace.dependencies]
anyhow = "1"
bitcode = "0.6"
chrono = { version = "0.4", default-features = false, features = ["alloc","std","clock","now"] }
clap = { version = "4.5", features = ["derive"] }
derive_builder = "0.20"
derive_more = { version = "2", features = ["full"] }
directories = "6"
env_logger = "0.11"
erased-serde = "0.4.8"
function_name = "0.3"
indexmap = "2.10"
indoc = "2"
heck = "0.5"
hashlink = { version = "0.10.0", features = ["serde"] }
libc = "0.2"
log = "0.4"
nohash-hasher = "0.2"
pretty_assertions = "1.4.1"
proc-macro2 = "1"
quote = "1"
rand = "0.9"
regex = "1"
ron = "0.10"
rkyv = "0.8"
rustc-hash = "2"
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-value = "0.7.0"
shellexpand = "3"
shutdown_hooks = "0.1"
snafu = "0.8"
stabby = { version = "72.1" }
strum = { version = "0.27", features = ["derive"] }
syn = { version = "2", features=["full"] }
thiserror = "2"
tar = "0.4"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
uzers = "0.12"
walkdir = "2.5"
widestring = "1"
xxhash-rust = { version = "0.8", features = ["xxh3", "const_xxh3"] }
zerocopy = { version = "0.8", features = ["derive"] }


sourcetrait_agnostic        = { path = "crates/sourcetrait_agnostic",           version = ">=0.0.0-0" }
sourcetrait_agnostic_bridge = { path = "crates/sourcetrait_agnostic_bridge",    version = ">=0.0.0-0" }
sourcetrait_cereal          = { path = "crates/sourcetrait_cereal",             version = ">=0.0.0-0" }
sourcetrait_cereal_macro    = { path = "crates/sourcetrait_cereal_macro",       version = ">=0.0.0-0" }
sourcetrait_chronox         = { path = "crates/sourcetrait_chronox",            version = ">=0.0.0-0" }
sourcetrait_clapx           = { path = "crates/sourcetrait_clapx",              version = ">=0.0.0-0" }
sourcetrait_datum           = { path = "crates/sourcetrait_datum",              version = ">=0.0.0-0" }
sourcetrait_dotrepo         = { path = "crates/sourcetrait_dotrepo",            version = ">=0.0.0-0" }
sourcetrait_gitparity       = { path = "crates/sourcetrait_gitparity",          version = ">=0.0.0-0" }
sourcetrait_ronx            = { path = "crates/sourcetrait_ronx",               version = ">=0.0.0-0" }
sourcetrait_ronx_macro      = { path = "crates/sourcetrait_ronx_macro",         version = ">=0.0.0-0" }
sourcetrait_stdx            = { path = "crates/sourcetrait_stdx",               version = ">=0.0.0-0" }
sourcetrait_sysgreen        = { path = "crates/sourcetrait_sysgreen",           version = ">=0.0.0-0" }
sourcetrait_testing         = { path = "crates/sourcetrait_testing",            version = ">=0.0.0-0" }
sourcetrait_testing_macro   = { path = "crates/sourcetrait_testing_macro",      version = ">=0.0.0-0" }
sourcetrait_tomlx           = { path = "crates/sourcetrait_tomlx",              version = ">=0.0.0-0" }
sourcetrait_tooling         = { path = "crates/sourcetrait_tooling",            version = ">=0.0.0-0" }
sourcetrait_twostr          = { path = "crates/sourcetrait_twostr",             version = ">=0.0.0-0" }

