[workspace]
resolver = "2"
members = [
    "packages/srctrait-common",
    "packages/srctrait-common-chronox",
    "packages/srctrait-common-clapx",
    "packages/srctrait-common-ronx",
    "packages/srctrait-common-stdx",
    "packages/srctrait-common-tomlx",
    "packages/srctrait-common-tooling",
    "packages/testing/srctrait-common-testing",
    "packages/testing/srctrait-common-testing-macro",
]

[workspace.dependencies]
clap = { version="4.5", features = ["derive"] }
chrono = "0.4"
ron = "0.10"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml = "0.8"

srctrait-common-stdx = { version="1", path="packages/srctrait-common-stdx" }
srctrait-common-testing = { path="packages/testing/srctrait-common-testing" }
