[package]
name = "asmov-common-dataset-enum"
version = "0.1.0"
description = "Enums traits for Asmov Common Dataset"
authors = ["Asmov LLC <development.pub@asmov.software>"]
repository = "https://github.com/asmov/common"
license = "AGPL-3.0-or-later"
keywords = ["model", "db", "sql"]
categories = []
edition = "2021"

[dependencies.asmov-common-traitenum-macro]
path = "../../packages/traitenum-macro"

[dependencies.asmov-common-traitenum]
path = "../../packages/traitenum"

[package.metadata.traitenum]
purpose = "lib"

[[package.metadata.traitenum.trait]]
name = "DatasetFieldEnum"
