[package]
name = "sourcetrait_tooling"
description = "Cross-platform system utilities"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
tar.workspace = true
walkdir.workspace = true

sourcetrait_stdx.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true
