[package]
name = "sourcetrait_stdx"
description = "Extended standard library for SourceTrait Common"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
chrono.workspace = true
serde = { workspace = true, optional = true }
stabby = { workspace = true, optional = true }

[features]
default = []
all = ["serde", "stabby"]
serde = ["dep:serde"]
stabby = ["dep:stabby"]

[dev-dependencies]
sourcetrait_testing.workspace = true
