[package]
name = "sourcetrait_gitparity"
description = "Git operations with parity between CLI and LibGit2"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
const_format = "0.2"
chrono.workspace = true
derive_builder.workspace = true
git2 = { version = "0.20", optional = true }
indoc.workspace = true
splitty = "1.0"
strum.workspace = true
thiserror.workspace = true
url = "2.5.4"
# testlib
hex = "0.4.3"

sourcetrait_stdx.workspace = true
sourcetrait_testing = { workspace = true, optional = true }

[features]
default = [ "gitc" ]
#default = [ "gitc", "nightly" ]
gitc = [ "dep:git2" ]
nightly = []
testlib = ["dep:sourcetrait_testing"]

[dev-dependencies]
env_logger.workspace = true 
log.workspace = true
sourcetrait_gitparity = { path = ".", features = ["testlib"] }
sourcetrait_testing.workspace = true
sourcetrait_stdx.workspace = true
