[package]
name = "asmov-common-linux"
version = "0.1.0"
description = "Linux platform library for Asmov Common"
authors = ["Asmov LLC <development.pub@asmov.software>"]
repository = "https://github.com/asmov/common"
license = "AGPL-3.0-or-later"
keywords = ["linux", "asmov", "common"]
categories = []
edition = "2021"

[dependencies]
home = "0"
