[package]
name = "asmov-common-dataset-wasm"
version = "0.1.0"
description = "WASM library Asmov Common Dataset"
authors = ["Asmov LLC <development.pub@asmov.software>"]
repository = "https://github.com/asmov/common"
license = "AGPL-3.0-or-later"
keywords = ["model", "db", "wasm"]
categories = []
edition = "2021"

[dependencies]
asmov-common-dataset = { path = "../dataset" }
serde = { version = "1", features = ["derive"] }
derive_builder = "0"

[dev-dependencies]
wasm-bindgen = { version = "0", features = ["serde"] }
wasm-bindgen-test = { version = "0" }
wasm-bindgen-futures = { version = "0" }
serde-wasm-bindgen = { version = "0" }
js-sys = { version = "0" }
