[package]
name = "sourcetrait_testing"
version = "4.3.1"
description = "Structured testing with setup, teardown, and standardized fixture and temp directories"
authors = ["SourceTrait <development@sourcetrait.com"]
license = "AGPL-3.0-or-later WITH GPL-3.0-linking-source-exception"
repository = "https://github.com/sourcetrait/sourcetrait_common"
homepage = "https://sourcetrait.com"
categories = ["development-tools::testing"]
keywords = ["sourcetrait", "common", "testing"]
edition = "2024"

[dependencies]
anyhow.workspace = true 
function_name.workspace = true 
indexmap.workspace = true
log.workspace = true
rand = "0.9"
regex.workspace = true
shutdown_hooks = "0.1"
sourcetrait_testing_macro = { version="1", path = "../sourcetrait_testing_macro" }
sourcetrait_tooling = { optional = true, version="2", path="../sourcetrait_tooling" }
env_logger.workspace = true 

[features]
default = ["tooling"]
#default = ["tooling", "nightly"]
nightly = []
tooling = ["sourcetrait_tooling"]

[[example]]
name = "example-fibonacci"
test = true

[[example]]
name = "example_test"
test = true
