[package]
name = "sourcetrait_testing"
description = "Structured testing with setup, teardown, and standardized fixture and temp directories"
version.workspace    = true
authors.workspace    = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true
homepage.workspace   = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
anyhow.workspace = true 
function_name.workspace = true 
indexmap.workspace = true
log.workspace = true
rand.workspace = true
regex.workspace = true
shutdown_hooks.workspace = true
sourcetrait_testing_macro.workspace = true
sourcetrait_tooling = { workspace = true, optional = true }
env_logger.workspace = true 
tokio = { workspace = true, optional = true }

[features]
default = ["tooling", "test_all"]
#default = ["tooling", "nightly"]
nightly = []
test_all = ["tokio"]
tooling = ["sourcetrait_tooling"]

[[example]]
name = "example-fibonacci"
test = true

[[example]]
name = "example_test"
test = true
