[package]
name = "sourcetrait_dotrepo"
version = "0.1.0"
description = "Multi-tenant .repo directory structure for file repository systems"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later WITH GPL-3.0-linking-source-exception"
repository = "https://github.com/sourcetrait/sourcetrait_common"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "common", "dotrepo"]
edition = "2024"

[dependencies]
derive_builder.workspace = true
ignore = "0.4"
indoc.workspace = true
semver.workspace = true
serde.workspace = true
strum.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true

#[[example]]
#name = "example"
#test = true
